---
- name: Set component_name
  set_fact:
    component_key: app
    component_value: counter-backend

- include_tasks: check_deployment.yml

- include_tasks: check_hpa.yml
  vars:
    maxReplicas: 2
    minReplicas: 1

- include_tasks: check_pod.yml

- include_tasks: check_route.yml

- include_tasks: check_service.yml